version: '3.8'
services:
  fuzzleton:
    container_name: fuzzleton
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "5173" 
    volumes:
      - .:/app  
      - /app/node_modules  # Prevent overwriting node_modules from the host
    environment:
      - NODE_ENV=production
    command: ["sh", "-c", "git lfs pull && npm start"]  # Ensure LFS is pulled before running the app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fuzzleton.rule=Host(`fuzzleton.tristan-patout.fr`)"
      - "traefik.http.routers.fuzzleton.entrypoints=websecure"
      - "traefik.http.routers.fuzzleton.tls.certresolver=myresolver"

networks:
  web:
    external: true
